version: "3"
services:
  api:
    build: .
    ports:
      - 8000:8000
#    env_file:
#      - ./.env
    environment:
      - DATABASE_HOSTNAME=localhost
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=password123
      - DATABASE_NAME=itet_db
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=384c8deba153680466e06247a7db533df934914219ba9ccd51c1cfc601fa9457
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=120